#!/bin/sh
mkdir med_res_imager
mkdir icon_imager
mkdir med_res_pnm
mkdir icon_pnm
if perl -Mblib -MImager -e '$im = Imager->new()->read(file=>"kscdisplay.png")->convert(preset=>"noalpha")->write(file=>"kscdisplay.jpg") or die' ; then
  time perl -Mblib=.. scale.perl kscdisplay.jpg
  time perl scale.sh.perl kscdisplay.jpg
fi