name: os-linux

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  os-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: install package dependencies cached
        uses: tonycoz/cache-apt-pkgs-action@v1-node-20-warning
        with:
            packages: install build-essential libtiff-dev libpng-dev libgif-dev libfreetype6-dev libjpeg-dev libtest-pod-coverage-perl libtest-pod-perl libpod-parser-perl libpod-spell-perl aspell libinline-c-perl libparse-recdescent-perl cpanminus libcapture-tiny-perl libmodule-build-perl
      -name: install CPAN dependencies
       run: |
            sudo cpanm Inline::CPP
      - name: checkout
        uses: actions/checkout@v6
      - name: configure
        run: |
          perl Makefile.PL
      - name: build
        run: |
            make -j2
      - name: test
        run: |
            HARNESS_OPTIONS=j2 IMAGER_AUTHOR_TESTING=1 make test
