name: os-netbsd

on:
  workflow_call:

jobs:
  os-netbsd:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: test in netbsd
        id: test
        uses: vmactions/netbsd-vm@v1
        with:
          prepare: |
            /usr/sbin/pkg_add -u perl tiff png giflib libjpeg-turbo freetype2 git
          run: |
            echo '::group::uname -a'
            uname -a
            echo -e '::endgroup::\n::group::perl -V'
            perl -V
            echo -e '::endgroup::\n::group::Configure'
            perl Makefile.PL
            echo -e '::endgroup::\n::group::Build'
            make -j2
            echo -e '::endgroup::\n::group::Tests'
            HARNESS_OPTIONS=j2 IMAGER_AUTHOR_TESTING=1 make test
            echo '::endgroup::'
