name: quality-valgrind

on:
  workflow_call:

jobs:
  quality-tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: install package dependencies cached
        uses: awalsh128/cache-apt-pkgs-action@v1.6.3
        with:
          packages: build-essential libtiff-dev libpng-dev libgif-dev libfreetype6-dev libjpeg-dev libtest-pod-coverage-perl libtest-pod-perl libpod-parser-perl libpod-spell-perl aspell libinline-c-perl libparse-recdescent-perl cpanminus libcapture-tiny-perl libmodule-build-perl clang-tidy libclang-dev bear
          version: 1.2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1.41.1
        with:
          perl-version: 5.42.0
          multi-thread: true
          install-modules:
            Inline::C
            Inline::CPP
            Parse::RecDescent
            Perl::OSType
      - name: perl -V
        run: perl -V
      - name: setup perl-check
        run: |
          wget https://github.com/tonycoz/perl-check/archive/refs/tags/v1.0.0.tar.gz
          tar xzf v1.0.0.tar.gz
          cd perl-check-1.0.0
          cmake -B build
          cmake --build build -v
          echo "PERL_CHECK=$(pwd)/build/libperl-check.so" >>$GITHUB_ENV
      - name: checkout
        uses: actions/checkout@v6
        with:
          path: imager
      - name: configure
        run: |
          cd imager && perl Makefile.PL
      - name: build
        run: |
          cd imager && bear -- make -j2
      - name: tidy
        run: |
          cd imager && run-clang-tidy -load "$PERL_CHECK" -config-file .github/clang-tidy
      - name: tidy-errors
        run: |
          cd imager && run-clang-tidy -load "$PERL_CHECK" -config-file .github/clang-tidy-errors
