name: reverse-deps

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  reverse-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: install dependencies
        run: |
            sudo apt-get update ||:
            sudo apt-get -y install build-essential libtiff-dev libpng-dev libgif-dev libfreetype6-dev libjpeg-dev libinline-c-perl libparse-recdescent-perl cpanminus libwebp-dev libheif-dev libheif-plugin-x265 libtest-warnings-perl libscope-guard-perl libsub-info-perl liblist-someutils-perl libtest-leaktrace-perl libtest-exception-perl libsub-uplevel-perl libgd-perl libterm-table-perl libmodule-pluggable-perl libmodule-build-perl libtest-fatal-perl libnet-http-perl libtest-requires-perl libtest-output-perl libcwd-guard-perl libmouse-perl libmodule-build-xsutil-perl libfile-copy-recursive-reduced-perl libdevel-checkcompiler-perl libextutils-helpers-perl libextutils-installpaths-perl libextutils-config-perl libtest-number-delta-perl libwww-perl libtest-needs-perl libnet-http-perl libhttp-daemon-perl libwww-robotrules-perl libfile-listing-perl libtest-requiresinternet-perl libhttp-negotiate-perl libdatetime-locale-perl libspecio-perl libfile-sharedir-install-perl ||:
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: |
          perl Makefile.PL
      - name: build
        run: |
            make -j2
      - name: test
        run: |
            HARNESS_OPTIONS=j2 IMAGER_AUTHOR_TESTING=1 make test
      - name: install
        run: sudo make install
      - name: Imager-File-WEBP
        run: cpanm --sudo -v Imager::File::WEBP
      - name: Imager-File-APNG
        run: cpanm --sudo -v Imager::File::APNG
      - name: Imager-File-QOI
        run: cpanm --sudo -v Imager::File::QOI
      - name: Imager-File-HEIF
        run: cpanm --sudo -v Imager::File::HEIF
      - name: Music::FretboardDiagram
        run: cpanm --sudo -v Music::FretboardDiagram
      - name: Image::PHash
        run: cpanm --sudo -v Image::PHash
      - name: Geo::OSM::Imager
        run: cpanm --sudo -v Geo::OSM::Imager
      - name: Imager::IMBarcode::JP
        run: cpanm --sudo -v Imager::IMBarcode::JP
      # https://rt.cpan.org/Public/Bug/Display.html?id=136799
      #- name: Graphics::Framebuffer
      #  run: cpanm --sudo-v Graphics::Framebuffer
      # needs perl 5.32, and ubuntu is 5.30
      #- name: Games::Simutrans::Pakset
      #  run: cpanm --sudo -v Games::Simutrans::Pakset
      - name: Tree::Cladogram
        run: cpanm --sudo -v Tree::Cladogram
      - name: Image::Checkerboard
        run: cpanm --sudo -v Image::Checkerboard
      - name: Image::Base::Imager
        run: cpanm --sudo -v Image::Base::Imager
      - name: Imager::Filter::Statistic
        run: cpanm --sudo -v Imager::Filter::Statistic
      - name: Imager::Barcode128
        run: cpanm --sudo -v Imager::Barcode128
      - name: Imager::Filter::Autocrop
        run: cpanm --sudo -v Imager::Filter::Autocrop
      - name: Imager::Filter::Bakumatsu
        run: cpanm --sudo -v Imager::Filter::Bakumatsu
      - name: Imager::Trim
        run: cpanm --sudo -v Imager::Trim
      - name: Ham::WorldMap
        run: cpanm --sudo -v Ham::WorldMap
      - name: Image::Select
        run: cpanm --sudo -v Image::Select
      - name: Imager::Filter::Statistic
        run: cpanm --sudo -v Imager::Filter::Statistic
      - name: Imager::QRCode
        run: cpanm --sudo -v Imager::QRCode
      - name: Image::JpegMinimal
        run: cpanm --sudo -v Image::JpegMinimal
      - name: Acme::DreamyImage
        run: cpanm --sudo -v Acme::DreamyImage
