name: reverse-deps

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  reverse-deps:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: install dependencies
        run: |
            sudo apt-get update ||:
            sudo apt-get -y install build-essential libtiff-dev libpng-dev libgif-dev libfreetype6-dev libjpeg-dev libinline-c-perl libparse-recdescent-perl cpanminus libwebp-dev libheif-dev libtest-warnings-perl libscope-guard-perl libsub-info-perl liblist-someutils-perl libtest-leaktrace-perl libtest-exception-perl libsub-uplevel-perl libgd-perl libterm-table-perl libmodule-pluggable-perl libmodule-build-perl libtest-fatal-perl libnet-http-perl libtest-requires-perl libtest-output-perl libcwd-guard-perl libmouse-perl libmodule-build-xsutil-perl libfile-copy-recursive-reduced-perl libdevel-checkcompiler-perl libextutils-helpers-perl libextutils-installpaths-perl libextutils-config-perl libtest-number-delta-perl libwww-perl libtest-needs-perl libnet-http-perl libhttp-daemon-perl libwww-robotrules-perl libfile-listing-perl libtest-requiresinternet-perl libhttp-negotiate-perl libdatetime-locale-perl libspecio-perl libfile-sharedir-install-perl
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: |
          perl Makefile.PL
      - name: build
        run: |
            make -j2
      - name: test
        run: |
            HARNESS_OPTIONS=j2 IMAGER_AUTHOR_TESTING=1 make test
      - name: install
        run: sudo make install
      - name: Test downstreams
        run: |
          result=0
          for name in $(grep -v '^#' .github/downstreams.txt) ; do
            echo "::group::Testing $name"
            if ! cpanm --sudo -v $name ; then
              result=1
              echo "::error ::$name failed"
            fi
          done
          exit $result
