name: test-linux-i386

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  imager:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container:
        image: i386/ubuntu:latest
        env:
            WORKSPACE: ${{ github.workspace }}
    steps:
      - name: install dependencies
        run: |
            apt-get update ||:
            apt-get -y install build-essential libtiff-dev libpng-dev libgif-dev libfreetype6-dev libjpeg-dev git-core
      - name: checkout
        uses: actions/checkout@v1
      - name: workaround
        run: "git config --global --add safe.directory /__w/imager/imager"
      - name: configure
        run: |
          perl Makefile.PL
      - name: build
        run: |
            make -j2
      - name: test
        run: |
            HARNESS_OPTIONS=j2 make test
