name: valgrind

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
  pull_request:


jobs:
  imager:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: install dependencies
        run: |
            sudo apt-get update ||:
            sudo apt-get -y install build-essential libtiff-dev libpng-dev libgif-dev libfreetype6-dev libjpeg-dev libtest-pod-coverage-perl libtest-pod-perl libpod-parser-perl libpod-spell-perl aspell libinline-c-perl libparse-recdescent-perl cpanminus valgrind
            # prerequisites for Inline::CPP
            sudo apt-get -y install libcapture-tiny-perl libmodule-build-perl
            sudo cpanm Inline::CPP
      - name: checkout
        uses: actions/checkout@v2
      - name: configure
        run: |
          perl Makefile.PL OPTIMIZE="-O0 -g"
      - name: build
        run: |
            make -j2
      - name: test
        run: |
            echo '::group::Imager'
            IMAGER_AUTHOR_TESTING=1 prove -e 'valgrind --error-exitcode=1 --suppressions=.github/valgrind.supp -q perl -Mblib' -r t
            echo '::endgroup::Imager'
            for subdir in FT2 GIF ICO JPEG PNG SGI TIFF ; do ( cd $subdir ; echo "::group::$subdir" ; prove -e 'valgrind --error-exitcode=1 --suppressions=../.github/valgrind.supp -q perl -Mblib' t ; echo "::endgroup::$subdir" ) done
